[2023-07-05 14:45:33,601] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.conexion_BD scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-05 14:45:33,609] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.conexion_BD scheduled__2023-07-04T00:00:00+00:00 [queued]>
[2023-07-05 14:45:33,610] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 14:45:33,611] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-05 14:45:33,611] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 14:45:33,623] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): conexion_BD> on 2023-07-04 00:00:00+00:00
[2023-07-05 14:45:33,630] {standard_task_runner.py:52} INFO - Started process 191 to run task
[2023-07-05 14:45:33,634] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'API_ETL', 'conexion_BD', 'scheduled__2023-07-04T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/API_ETL.py', '--cfg-path', '/tmp/tmppjpdfh42', '--error-file', '/tmp/tmpo4p6esg_']
[2023-07-05 14:45:33,636] {standard_task_runner.py:80} INFO - Job 29: Subtask conexion_BD
[2023-07-05 14:45:33,710] {task_command.py:371} INFO - Running <TaskInstance: API_ETL.conexion_BD scheduled__2023-07-04T00:00:00+00:00 [running]> on host c8adaca8488b
[2023-07-05 14:45:33,753] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-05 14:45:33,788] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DylanKaplan
AIRFLOW_CTX_DAG_ID=API_ETL
AIRFLOW_CTX_TASK_ID=conexion_BD
AIRFLOW_CTX_EXECUTION_DATE=2023-07-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-04T00:00:00+00:00
[2023-07-05 14:45:33,791] {logging_mixin.py:115} INFO - Conectandose a la BD en la fecha: 2023-07-04 0
[2023-07-05 14:45:35,175] {logging_mixin.py:115} INFO - <connection object at 0xffff7d699590; dsn: 'user=kaplan46611_coderhouse password=xxx dbname=data-engineer-database host=data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com port=5439', closed: 0>
[2023-07-05 14:45:35,176] {logging_mixin.py:115} INFO - Connected to Redshift successfully!
[2023-07-05 14:45:35,177] {python.py:173} INFO - Done. Returned value was: None
[2023-07-05 14:45:35,192] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=API_ETL, task_id=conexion_BD, execution_date=20230704T000000, start_date=20230705T144533, end_date=20230705T144535
[2023-07-05 14:45:35,236] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-05 14:45:35,282] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
