[2023-07-05 23:28:24,736] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.email manual__2023-07-05T23:23:20.292023+00:00 [queued]>
[2023-07-05 23:28:24,744] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.email manual__2023-07-05T23:23:20.292023+00:00 [queued]>
[2023-07-05 23:28:24,744] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 23:28:24,745] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-07-05 23:28:24,746] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 23:28:24,757] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): email> on 2023-07-05 23:23:20.292023+00:00
[2023-07-05 23:28:24,763] {standard_task_runner.py:52} INFO - Started process 237 to run task
[2023-07-05 23:28:24,769] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'API_ETL', 'email', 'manual__2023-07-05T23:23:20.292023+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/API_ETL.py', '--cfg-path', '/tmp/tmpti79uvy7', '--error-file', '/tmp/tmpeysg8w9g']
[2023-07-05 23:28:24,770] {standard_task_runner.py:80} INFO - Job 104: Subtask email
[2023-07-05 23:28:24,839] {task_command.py:371} INFO - Running <TaskInstance: API_ETL.email manual__2023-07-05T23:23:20.292023+00:00 [running]> on host 8a8d74a7cb9c
[2023-07-05 23:28:24,877] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-05 23:28:24,913] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DylanKaplan
AIRFLOW_CTX_DAG_ID=API_ETL
AIRFLOW_CTX_TASK_ID=email
AIRFLOW_CTX_EXECUTION_DATE=2023-07-05T23:23:20.292023+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-05T23:23:20.292023+00:00
[2023-07-05 23:28:24,929] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/API_ETL.py", line 87, in enviar
    if dataframe['Vino'].astype(float).mean() > 13.0:
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5815, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 418, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 327, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 591, in astype
    new_values = astype_array_safe(values, dtype, copy=copy, errors=errors)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1309, in astype_array_safe
    new_values = astype_array(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1257, in astype_array
    values = astype_nansafe(values, dtype, copy=copy)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1201, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'Vino'
[2023-07-05 23:28:24,946] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=API_ETL, task_id=email, execution_date=20230705T232320, start_date=20230705T232824, end_date=20230705T232824
[2023-07-05 23:28:24,955] {standard_task_runner.py:97} ERROR - Failed to execute job 104 for task email (could not convert string to float: 'Vino'; 237)
[2023-07-05 23:28:24,982] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-07-05 23:28:25,021] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
