[2023-07-05 23:38:17,750] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.email manual__2023-07-05T23:38:14.512175+00:00 [queued]>
[2023-07-05 23:38:17,757] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.email manual__2023-07-05T23:38:14.512175+00:00 [queued]>
[2023-07-05 23:38:17,758] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 23:38:17,759] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-05 23:38:17,759] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 23:38:17,771] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): email> on 2023-07-05 23:38:14.512175+00:00
[2023-07-05 23:38:17,777] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2023-07-05 23:38:17,782] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'API_ETL', 'email', 'manual__2023-07-05T23:38:14.512175+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/API_ETL.py', '--cfg-path', '/tmp/tmp_gr5vfn_', '--error-file', '/tmp/tmpgq2y2uhd']
[2023-07-05 23:38:17,784] {standard_task_runner.py:80} INFO - Job 132: Subtask email
[2023-07-05 23:38:17,854] {task_command.py:371} INFO - Running <TaskInstance: API_ETL.email manual__2023-07-05T23:38:14.512175+00:00 [running]> on host 8a8d74a7cb9c
[2023-07-05 23:38:17,891] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-05 23:38:17,938] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DylanKaplan
AIRFLOW_CTX_DAG_ID=API_ETL
AIRFLOW_CTX_TASK_ID=email
AIRFLOW_CTX_EXECUTION_DATE=2023-07-05T23:38:14.512175+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-05T23:38:14.512175+00:00
[2023-07-05 23:38:17,957] {logging_mixin.py:115} INFO - Enviando mail. Fecha: 2023-07-05 23
[2023-07-05 23:38:19,364] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xe1' in position 21: ordinal not in range(128)
[2023-07-05 23:38:19,366] {logging_mixin.py:115} INFO - Failure
[2023-07-05 23:38:19,368] {python.py:173} INFO - Done. Returned value was: None
[2023-07-05 23:38:19,397] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=API_ETL, task_id=email, execution_date=20230705T233814, start_date=20230705T233817, end_date=20230705T233819
[2023-07-05 23:38:19,445] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-05 23:38:19,486] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
