[2023-07-05 20:17:59,160] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.email manual__2023-07-05T20:17:44.552696+00:00 [queued]>
[2023-07-05 20:17:59,168] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: API_ETL.email manual__2023-07-05T20:17:44.552696+00:00 [queued]>
[2023-07-05 20:17:59,169] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 20:17:59,170] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-07-05 20:17:59,170] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-07-05 20:17:59,186] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): email> on 2023-07-05 20:17:44.552696+00:00
[2023-07-05 20:17:59,193] {standard_task_runner.py:52} INFO - Started process 204 to run task
[2023-07-05 20:17:59,198] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'API_ETL', 'email', 'manual__2023-07-05T20:17:44.552696+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/API_ETL.py', '--cfg-path', '/tmp/tmpsaudbel7', '--error-file', '/tmp/tmpuny3rzn1']
[2023-07-05 20:17:59,201] {standard_task_runner.py:80} INFO - Job 40: Subtask email
[2023-07-05 20:17:59,285] {task_command.py:371} INFO - Running <TaskInstance: API_ETL.email manual__2023-07-05T20:17:44.552696+00:00 [running]> on host 7d160dc60e25
[2023-07-05 20:17:59,323] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-07-05 20:17:59,362] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=DylanKaplan
AIRFLOW_CTX_DAG_ID=API_ETL
AIRFLOW_CTX_TASK_ID=email
AIRFLOW_CTX_EXECUTION_DATE=2023-07-05T20:17:44.552696+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-05T20:17:44.552696+00:00
[2023-07-05 20:17:59,365] {logging_mixin.py:115} INFO - Enviando mail: 2023-07-05 20
[2023-07-05 20:18:01,073] {logging_mixin.py:115} INFO - 'ascii' codec can't encode character '\xe9' in position 549: ordinal not in range(128)
[2023-07-05 20:18:01,075] {logging_mixin.py:115} INFO - Failure
[2023-07-05 20:18:01,077] {python.py:173} INFO - Done. Returned value was: None
[2023-07-05 20:18:01,103] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=API_ETL, task_id=email, execution_date=20230705T201744, start_date=20230705T201759, end_date=20230705T201801
[2023-07-05 20:18:01,142] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-07-05 20:18:01,175] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
